spring.application.name=kabootar-multi-region-simulator
server.port=8082


#Pass these as variables to simulate traffic across region
app.simulator.region-name=ap-south-mumbai
app.simulator.instance-name=demo-mumbai-01
app.simulator.service-name=demo-service