spring.application.name=kabootar-multi-region-simulator
server.port=8082
management.endpoints.web.exposure.include=health,info,metrics,prometheus
server.servlet.context-path=/simulator

# Actuator Properties
management.endpoint.health.status.order=DOWN, OUT_OF_SERVICE, DEGRADED, UNKNOWN, UP
management.endpoint.health.status.http-mapping.DEGRADED=503
management.endpoint.health.show-details=always



#Pass these as variables to simulate traffic across region
app.simulator.region-name=ap-south-mumbai
app.simulator.instance-name=demo-mumbai-01
app.simulator.service-name=demo-service



# OpenTelemetry Propeties
# Added for local testing
# ToDo: Change this later
management.tracing.sampling.probability=1.0

# Obersvability Config
management.opentelemetry.tracing.export.otlp.endpoint=http://otel-collector:4318/v1/traces

# Need this to enable HTTP histograms
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Hide detailed health information from the endpoint response.
management.endpoint.health.show-details=never