CREATE TABLE services (
    id VARCHAR(255) NOT NULL,
    `key` VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_services PRIMARY KEY (id),
    CONSTRAINT uk_services_key UNIQUE (`key`)
)ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;