spring.datasource.url=jdbc:mariadb://172.21.0.2/kabootar_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mypass

spring.data.redis.host=localhost
spring.data.redis.port=6379