spring.application.name=configuration

spring.flyway.locations=classpath:db/migration
# Disable Hibernate's automatic schema creation to let Flyway handle it
spring.jpa.hibernate.ddl-auto=update


# Optional Flyway Configurations
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false



# Import local .env file if it exists (ignored if missing in production)
spring.config.import=optional:file:.env[.properties]

# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection so integration tests can run
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Keep the connection alive if idle for a long time (needed in production)
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=VARCHAR
spring.jpa.open-in-view=false

debug=false

# Actuator Config

management.endpoints.web.exposure.include=health,info

# Enables Spring Boot liveness and readiness probes.
# Liveness answers: "Is the application alive?"
# Readiness answers: "Is the application ready to receive traffic?"
management.endpoint.health.probes.enabled=true



# Optional: livenessState is used by default
# this property can be omitted, but we have added it to add other check if needed in future
# Example: livenessState,customHealth
management.endpoint.health.group.liveness.include=livenessState

# Readiness checks whether the application is ready to receive traffic.
# Add required dependencies here, e.g. readinessState,db,redis.
management.endpoint.health.group.readiness.include=readinessState,db

# Hide detailed health information from the endpoint response.
management.endpoint.health.show-details=never
