spring.datasource.url=${KABOOTAR_DB_URL}
spring.datasource.username=${KABOOTAR_DB_USERNAME}
spring.datasource.password=${KABOOTAR_DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

# ===============================
# = CACHE SOURCE
# ===============================
spring.data.redis.host=${KABOOTAR_CACHE_URL}
spring.data.redis.port=${KABOOTAR_CACHE_PORT}


# ===============================
# = FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true