spring.application.name=alert

# Actuator Config

management.endpoints.web.exposure.include=health,info

# Enables Spring Boot liveness and readiness probes.
# Liveness answers: "Is the application alive?"
# Readiness answers: "Is the application ready to receive traffic?"
management.endpoint.health.probes.enabled=true



# Optional: livenessState is used by default
# this property can be omitted, but we have added it to add other check if needed in future
# Example: livenessState,customHealth
management.endpoint.health.group.liveness.include=livenessState

# Readiness checks whether the application is ready to receive traffic.
# Add required dependencies here, e.g. readinessState,db,redis.
management.endpoint.health.group.readiness.include=readinessState